"""Render `architecture.excalidraw` to PDF/PNG via matplotlib.

Parses the JSON Excalidraw source (40 elements) and reproduces the
informative original Figure 1 layout for the npj DM submission. Replaces
the matplotlib placeholder previously generated by
`build_npj_overleaf_figures.py::fig_pipeline_architecture`.
"""
from __future__ import annotations

import json
from pathlib import Path

import matplotlib.pyplot as plt
from matplotlib.patches import FancyBboxPatch, FancyArrowPatch

REPO = Path(__file__).resolve().parents[1]
SRC = REPO / "outputs" / "paper_v2" / "figures" / "architecture.excalidraw"
OUT_DIR = REPO / "outputs" / "paper_v2" / "figures"


def _hex_with_alpha(color: str | None, alpha: float = 1.0):
    if color is None or color == "transparent":
        return (0, 0, 0, 0)
    return color


def main() -> None:
    with SRC.open() as f:
        data = json.load(f)
    elements = data["elements"]

    # Compute bounding box of all geometry
    xs, ys, x2s, y2s = [], [], [], []
    for el in elements:
        x = el.get("x", 0)
        y = el.get("y", 0)
        w = el.get("width", 0)
        h = el.get("height", 0)
        xs.append(x)
        ys.append(y)
        x2s.append(x + w)
        y2s.append(y + h)
    minx, miny = min(xs), min(ys)
    maxx, maxy = max(x2s), max(y2s)
    src_w = maxx - minx
    src_h = maxy - miny

    # Aspect-preserving matplotlib figure. Cap width 14in.
    fig_w = 14.0
    fig_h = fig_w * (src_h / src_w)
    fig, ax = plt.subplots(figsize=(fig_w, fig_h))
    ax.set_xlim(minx - 20, maxx + 20)
    ax.set_ylim(maxy + 20, miny - 20)  # invert y to match Excalidraw
    ax.set_aspect("equal")
    ax.axis("off")

    # Render rectangles
    for el in elements:
        if el["type"] != "rectangle":
            continue
        x, y = el["x"], el["y"]
        w, h = el["width"], el["height"]
        stroke = el.get("strokeColor", "#1e1e1e")
        fill = el.get("backgroundColor", "transparent")
        if fill == "transparent":
            fill_rgba = (0, 0, 0, 0)
        else:
            fill_rgba = fill
        sw = el.get("strokeWidth", 1)
        rect = FancyBboxPatch(
            (x, y), w, h,
            boxstyle="round,pad=2,rounding_size=6",
            linewidth=sw * 1.1, edgecolor=stroke, facecolor=fill_rgba,
            zorder=1,
        )
        ax.add_patch(rect)

    # Render text
    for el in elements:
        if el["type"] != "text":
            continue
        x, y = el["x"], el["y"]
        w = el.get("width", 0)
        h = el.get("height", 0)
        text = el.get("text", "")
        fs_px = el.get("fontSize", 16)
        # Excalidraw fontSize is roughly px; matplotlib uses pt. Use scaled pt.
        fs_pt = fs_px * 0.75
        color = el.get("strokeColor", "#1e1e1e")
        text_align = el.get("textAlign", "left")
        font_family = el.get("fontFamily", 1)
        # Map Excalidraw font family: 1=hand, 2=sans, 3=mono. Use sans for legibility.
        family = "monospace" if font_family == 3 else "sans-serif"
        if text_align == "center":
            tx = x + w / 2
            ha = "center"
        elif text_align == "right":
            tx = x + w
            ha = "right"
        else:
            tx = x
            ha = "left"
        ax.text(
            tx, y + h / 2, text,
            ha=ha, va="center",
            fontsize=fs_pt, color=color,
            family=family, zorder=3,
        )

    # Render arrows
    for el in elements:
        if el["type"] != "arrow":
            continue
        x0, y0 = el["x"], el["y"]
        points = el.get("points", [])
        if not points:
            continue
        # Convert relative point list to absolute
        path_pts = [(x0 + px, y0 + py) for px, py in points]
        stroke = el.get("strokeColor", "#1e1e1e")
        sw = el.get("strokeWidth", 1)
        style = el.get("strokeStyle", "solid")
        ls = "--" if style == "dashed" else "-"
        # Draw segments
        for (xa, ya), (xb, yb) in zip(path_pts[:-1], path_pts[1:]):
            ax.plot([xa, xb], [ya, yb], color=stroke, linewidth=sw * 1.1,
                    linestyle=ls, zorder=2)
        # Arrowhead at the last segment
        (xa, ya), (xb, yb) = path_pts[-2], path_pts[-1]
        arrow = FancyArrowPatch(
            (xa, ya), (xb, yb),
            arrowstyle="-|>", mutation_scale=14,
            color=stroke, linewidth=sw * 1.1,
            linestyle=ls if ls == "-" else "-",  # arrowhead always solid
            zorder=2,
        )
        ax.add_patch(arrow)

    fig.tight_layout()
    pdf_out = OUT_DIR / "pipeline_architecture.pdf"
    png_out = OUT_DIR / "pipeline_architecture.png"
    fig.savefig(pdf_out, bbox_inches="tight")
    fig.savefig(png_out, bbox_inches="tight", dpi=200)
    plt.close(fig)
    print(f"[wrote] {pdf_out}")
    print(f"[wrote] {png_out}")


if __name__ == "__main__":
    main()
